groups:
- name: NginxAlerts
  rules:
  - alert: NginxDown
    expr: up{job="nginx"} == 0
    for: 1m
    labels:
      severity: 'critical'
    annotations:
      summary: "NGINX service is down"
      description: "The NGINX service on {{ $labels.instance }} is not responding."

  - alert: HighCpuUsage
    expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 90
    for: 5m
    labels:
      severity: 'warning'
    annotations:
      summary: "High CPU usage detected"
      description: "CPU usage on instance {{ $labels.instance }} is over 90%."
